version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - kind/dependency
  ignore:
  - dependency-name: Microsoft.Extensions.Logging.Console
    versions:
    - ">= 3.0.a, < 3.1"
  - dependency-name: Microsoft.Extensions.Logging.Console
    versions:
    - ">= 3.1.a, < 3.2"
  - dependency-name: Microsoft.Extensions.Logging.Filter
    versions:
    - "> 1.1.1, < 1.2"
  - dependency-name: Microsoft.NETCore.UniversalWindowsPlatform
    versions:
    - "> 6.2.8"
  - dependency-name: Uno.UI.RemoteControl
    versions:
    - 3.4.0
    - 3.5.1
    - 3.6.6
    - 3.7.0
  - dependency-name: Uno.UI
    versions:
    - 3.1.12
    - 3.1.14
    - 3.5.1
    - 3.6.6
    - 3.7.0
  - dependency-name: Uno.Wasm.Bootstrap
    versions:
    - 1.3.6
    - 2.0.0
  - dependency-name: Uno.Core
    versions:
    - 2.1.0
    - 2.2.0
