jobs:
- job: Packages

  pool:
    vmImage: 'windows-2019'

  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache
    ANDROID_NDK_HOME: C:\Microsoft\AndroidNDK64\android-ndk-r16b
    ANDROID_NDK_PATH: C:\Microsoft\AndroidNDK64\android-ndk-r16b

  steps:
  - checkout: self
    clean: true

  - task: GitVersion@5
    inputs:
      updateAssemblyInfo: false

  - task: MSBuild@1
    inputs:
      solution: src/MyApp.sln
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release "/p:Platform=Any CPU" /detailedsummary "/p:PackageVersion=$(GITVERSION.FullSemVer)" "/p:InformationalVersion=$(GITVERSION.InformationalVersion)"
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false